name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 

      - name: Build
        run: |
          chmod +x i686-elf-build.sh
          ./i686-elf-build.sh 
