name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  GCC_VERSION: 12.2.0
  BINUTILS_VERSION: 2.39
  TARGET_TRIPLE: i686-elf
  PREFIX: "/tmp/toolchain"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: |
          sudo apt update
          sudo apt -y install mtools libgmp-dev libmpfr-dev libmpc-dev

      - name: Download Binutils
        run: |
          wget https://ftp.gnu.org/gnu/binutils/binutils-${BINUTILS_VERSION}.tar.gz
          tar -xvf binutils-${BINUTILS_VERSION}.tar.gz

      - name: Build ${{ env.TARGET_TRIPLE }}-binutils
        run: |
          mkdir build-binutils
          cd build-binutils
          ../binutils-${BINUTILS_VERSION}/configure --target=${{ env.TARGET_TRIPLE }} --prefix="${{ env.PREFIX }}" --with-sysroot --disable-nls --disable-werror
          make
          make install

      - name: Download GCC
        run: |
          wget https://ftp.gnu.org/gnu/gcc/gcc-${GCC_VERSION}/gcc-${GCC_VERSION}.tar.gz
          tar -xvf gcc-${GCC_VERSION}.tar.gz

      - name: Build ${{ env.TARGET_TRIPLE }}-gcc
        run: |
          mkdir build-gcc
          cd build-gcc
          ../gcc-${GCC_VERSION}/configure --target=${{ env.TARGET_TRIPLE }} --prefix="${{ env.PREFIX }}" --disable-nls --enable-languages=c,c++ --without-headers
          make all-gcc
          make all-target-libgcc
          make install-gcc
          make install-target-libgcc

      - name: Package
        run: |
          cd /tmp
          tar -czf i686-elf.tar.gz toolchains

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: /tmp/i686-elf.tar.gz
          tag: artifact
          overwrite: true
