name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install packages
        run: |
          sudo apt update
          sudo apt -y install mtools libgmp-dev libmpfr-dev libmpc-dev

      - name: Build
        run: |
          chmod +x i686-elf-build.sh
          ./i686-elf-build.sh

      - name: Package
        run: |
          cd /tmp
          tar -czf i686-elf.tar.gz toolchains

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: /tmp/i686-elf.tar.gz
          tag: artifact
          overwrite: true
